from .AST import *

constInta = ASTDeclareValue(valueId="a", isConst=True, valueType="INT", )
constIntb = ASTDeclareValue(valueId="b", isConst=True, valueType="INT", )
constIntc = ASTDeclareValue(valueId="c", isConst=True, valueType="INT", )
constIntd = ASTDeclareValue(valueId="d", isConst=True, valueType="INT", )
constChara = ASTDeclareValue(valueId="a", isConst=True, valueType="CHAR", )
constCharb = ASTDeclareValue(valueId="b", isConst=True, valueType="CHAR", )
constCharc = ASTDeclareValue(valueId="c", isConst=True, valueType="CHAR", )
constChard = ASTDeclareValue(valueId="d", isConst=True, valueType="CHAR", )
inta = ASTDeclareValue(valueId="a", valueType="INT", )
intb = ASTDeclareValue(valueId="b", valueType="INT", )
intc = ASTDeclareValue(valueId="c", valueType="INT", )
intd = ASTDeclareValue(valueId="d", valueType="INT", )
chara = ASTDeclareValue(valueId="a", valueType="CHAR", )
charb = ASTDeclareValue(valueId="b", valueType="CHAR", )
charc = ASTDeclareValue(valueId="c", valueType="CHAR", )
chard = ASTDeclareValue(valueId="d", valueType="CHAR", )
arrayInta=ASTDeclareArray(valueId="a",valueType="INT")
arrayIntb=ASTDeclareArray(valueId="b",valueType="INT")
arrayIntc=ASTDeclareArray(valueId="c",valueType="INT")
arrayIntd=ASTDeclareArray(valueId="d",valueType="INT")
arrayChara=ASTDeclareArray(valueId="a",valueType="CHAR")
arrayCharb=ASTDeclareArray(valueId="b",valueType="CHAR")
arrayCharc=ASTDeclareArray(valueId="c",valueType="CHAR")
arrayChard=ASTDeclareArray(valueId="d",valueType="CHAR")
voidFuna=ASTDeclareFun(valueId="funa",returnType="VOID")
voidFunb=ASTDeclareFun(valueId="funb",returnType="VOID")
voidFunc=ASTDeclareFun(valueId="func",returnType="VOID")
voidFund=ASTDeclareFun(valueId="fund",returnType="VOID")
intFuna=ASTDeclareFun(valueId="funa",returnType="INT")
intFunb=ASTDeclareFun(valueId="funb",returnType="INT")
intFunc=ASTDeclareFun(valueId="func",returnType="INT")
intFund=ASTDeclareFun(valueId="fund",returnType="INT")
charFuna=ASTDeclareFun(valueId="funa",returnType="CHAR")
charFunb=ASTDeclareFun(valueId="funb",returnType="CHAR")
charFunc=ASTDeclareFun(valueId="func",returnType="CHAR")
charFund=ASTDeclareFun(valueId="fund",returnType="CHAR")
main=ASTDeclareFun(valueId="main",returnType="VOID")
